/**
 * Insights — the longitudinal payoff. Headline stats, a 30-day mood trend, and
 * recurring themes are computed locally from your entries. The weekly read and
 * the premium monthly report are generated by OpenRouter (cached in the
 * insights store, regenerated only when your journal changes).
 */

import React, { useEffect, useMemo } from 'react';
import { ActivityIndicator, View } from 'react-native';
import { useRouter } from 'expo-router';
import {
  useJournal,
  averageMood,
  moodByDay,
  themeFrequency,
  computeStreak,
} from '../../src/data/store';
import { usePremium } from '../../src/data/subscription';
import { useInsights, WEEKLY_MIN, MONTHLY_MIN } from '../../src/data/insights';
import { monthLabel, daysBetween } from '../../src/lib/date';
import { moodMeta } from '../../src/lib/mood';
import { useTheme } from '../../src/theme/ThemeProvider';
import { ScreenScrollView } from '../../src/components/ui/ScreenScrollView';
import { Text } from '../../src/components/ui/Text';
import { Button } from '../../src/components/ui/Button';
import { Card } from '../../src/components/ui/Surface';
import {
  SectionHeader,
  MoodTrendChart,
  InsightCard,
  MonthlyReportCard,
} from '../../src/components/journal';
import type { Mood } from '../../src/data/types';

function StatTile({ value, label, tint }: { value: string; label: string; tint?: string }) {
  const t = useTheme();
  return (
    <View
      style={{
        flex: 1,
        backgroundColor: t.colors.surface,
        borderRadius: t.radius.lg,
        borderWidth: 1,
        borderColor: t.colors.border,
        paddingVertical: t.space[4],
        paddingHorizontal: t.space[4],
        gap: 4,
      }}
    >
      <Text variant="monoLarge" tint={tint ?? t.colors.text}>
        {value}
      </Text>
      <Text variant="caption" color="textMuted">
        {label}
      </Text>
    </View>
  );
}

function ThemeBars({ entries }: { entries: ReturnType<typeof themeFrequency> }) {
  const t = useTheme();
  const max = entries[0]?.count ?? 1;
  return (
    <View style={{ gap: t.space[3] }}>
      {entries.map((row) => (
        <View key={row.tag} style={{ gap: 6 }}>
          <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
            <Text variant="body" color="textSecondary">
              {row.tag}
            </Text>
            <Text variant="mono" color="textMuted">
              {row.count}
            </Text>
          </View>
          <View
            style={{
              height: 6,
              borderRadius: 3,
              backgroundColor: t.colors.surfaceMuted,
              overflow: 'hidden',
            }}
          >
            <View
              style={{
                width: `${Math.max(8, (row.count / max) * 100)}%`,
                height: '100%',
                borderRadius: 3,
                backgroundColor: t.colors.accent,
              }}
            />
          </View>
        </View>
      ))}
    </View>
  );
}

/** The free weekly observation — generated, with loading / error / empty states. */
function WeeklyRead({
  status,
  error,
  text,
  enough,
  onRetry,
}: {
  status: 'idle' | 'loading' | 'error';
  error?: string | null;
  text?: string;
  enough: boolean;
  onRetry: () => void;
}) {
  const t = useTheme();
  const showSpinner = !text && (status === 'loading' || (enough && status !== 'error'));

  return (
    <View
      style={{
        borderRadius: t.radius.xl,
        borderWidth: 1,
        borderColor: t.colors.border,
        backgroundColor: t.colors.surface,
        padding: t.space[5],
        gap: t.space[3],
        ...t.shadow('sm'),
      }}
    >
      <Text variant="overline" color="accentText">
        This week’s read
      </Text>

      {!enough ? (
        <Text variant="serifBody" color="textSecondary">
          Write a few more times this week and your first read will appear here.
        </Text>
      ) : showSpinner ? (
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: t.space[3] }}>
          <ActivityIndicator color={t.colors.accent} />
          <Text variant="body" color="textMuted">
            Reading your week…
          </Text>
        </View>
      ) : text ? (
        <>
          <Text variant="serifBody" color="text">
            {text}
          </Text>
          <View style={{ flexDirection: 'row', justifyContent: 'flex-end' }}>
            <Button label="Refresh" variant="ghost" size="sm" onPress={onRetry} />
          </View>
        </>
      ) : status === 'error' ? (
        <View style={{ gap: t.space[2] }}>
          <Text variant="body" color="textSecondary">
            Couldn’t generate the read.
          </Text>
          {error ? (
            <Text variant="caption" color="textMuted">
              {error}
            </Text>
          ) : null}
          <Button label="Try again" variant="secondary" size="sm" onPress={onRetry} />
        </View>
      ) : null}
    </View>
  );
}

export default function InsightsScreen() {
  const t = useTheme();
  const router = useRouter();
  const isPremium = usePremium();
  const entries = useJournal((s) => s.entries);

  const {
    weekly,
    weeklyStatus,
    weeklyError,
    generateWeekly,
    report,
    reportStatus,
    reportError,
    generateReport,
  } = useInsights();

  const month = useMemo(() => moodByDay(entries, 30), [entries]);
  const avg30 = useMemo(() => averageMood(entries, 30), [entries]);
  const streak = useMemo(() => computeStreak(entries), [entries]);
  const themes = useMemo(() => themeFrequency(entries, 30).slice(0, 5), [entries]);
  const writtenDays = useMemo(() => month.filter((d) => d.count > 0).length, [month]);

  // entry counts in each window — drive the "enough data" states (same
  // calendar-day window the insights store uses)
  const weekCount = useMemo(
    () => entries.filter((e) => daysBetween(new Date(), new Date(e.createdAt)) <= 7).length,
    [entries],
  );
  const monthCount = useMemo(
    () => entries.filter((e) => daysBetween(new Date(), new Date(e.createdAt)) <= 30).length,
    [entries],
  );

  const avgMeta = avg30 != null ? moodMeta(Math.round(avg30) as Mood) : null;

  // generate (no-ops when cached & unchanged, or when below the entry minimum)
  useEffect(() => {
    generateWeekly(entries);
  }, [entries, generateWeekly]);

  useEffect(() => {
    if (isPremium) generateReport(entries, monthLabel());
  }, [entries, isPremium, generateReport]);

  return (
    <ScreenScrollView contentStyle={{ gap: t.space[6] }}>
      <View style={{ marginTop: t.space[2] }}>
        <SectionHeader eyebrow={monthLabel().toUpperCase()} title="Insights" />
      </View>

      {/* stat tiles */}
      <View style={{ flexDirection: 'row', gap: t.space[3] }}>
        <StatTile
          value={avg30 != null ? avg30.toFixed(1) : '—'}
          label={avgMeta ? `avg mood · ${avgMeta.label}` : 'avg mood · 30d'}
          tint={avgMeta?.color}
        />
        <StatTile value={`${writtenDays}`} label="days written · 30d" />
        <StatTile value={`${streak}`} label="day streak" tint={t.colors.accentText} />
      </View>

      {/* mood trend */}
      <Card elevation="sm" style={{ gap: t.space[4] }}>
        <SectionHeader eyebrow="Last 30 days" title="Mood over time" />
        <MoodTrendChart data={month} />
      </Card>

      {/* themes */}
      {themes.length > 0 ? (
        <Card elevation="sm" style={{ gap: t.space[4] }}>
          <SectionHeader eyebrow="What you write about" title="Recurring themes" />
          <ThemeBars entries={themes} />
        </Card>
      ) : null}

      {/* the free weekly read — generated */}
      <WeeklyRead
        status={weeklyStatus}
        error={weeklyError}
        text={weekly?.text}
        enough={weekCount >= WEEKLY_MIN}
        onRetry={() => generateWeekly(entries, true)}
      />

      {/* monthly report — gated on Premium */}
      {isPremium ? (
        <MonthlyReportCard
          report={report?.data ?? null}
          status={reportStatus}
          error={reportError}
          onRetry={() => generateReport(entries, monthLabel(), true)}
          written={writtenDays}
          avgLabel={avgMeta?.label}
          avgColor={avgMeta?.color}
          enoughData={monthCount >= MONTHLY_MIN}
        />
      ) : (
        <InsightCard
          locked
          eyebrow="Monthly report"
          title={`Your ${monthLabel().split(' ')[0]}, read closely`}
          body="A deep, longitudinal read of the month — patterns across mood and themes, what shifted, and the throughlines you can’t see day to day."
          bullets={[
            'Mood × theme correlations across the whole month',
            'What changed since last month',
            'The decisions and moments that defined it',
          ]}
          ctaLabel="Unlock the monthly report"
          onUnlock={() => router.push('/paywall')}
        />
      )}

      <Text variant="caption" color="textMuted" align="center">
        Observations are reflections, not advice.
      </Text>
    </ScreenScrollView>
  );
}
